# TODO: Unify this dockerfile into a single file that is parameterized by the app name.
FROM golang:1.20-alpine as builder
RUN apk --no-cache add git gcc libc-dev linux-headers

WORKDIR /go/src/app
COPY . .
RUN go mod vendor && mkdir -p dist

ARG APP_NAME=spectre
ARG APP_VERSION

ARG CGO_ENABLED=0
RUN go build -ldflags "-X github.com/chronicleprotocol/oracle-suite.Version=$APP_VERSION" \
    -o dist/$APP_NAME ./cmd/$APP_NAME
RUN ./dist/$APP_NAME --version

FROM alpine:3.16
RUN apk --no-cache add ca-certificates

# TODO: why root?
WORKDIR /root
COPY --from=builder /go/src/app/dist/* /usr/local/bin/
COPY ./config-*.hcl ./cmd/spectre/config.hcl /usr/share/oracle-suite/

ENTRYPOINT ["/usr/local/bin/spectre"]
CMD ["-c", "/usr/share/oracle-suite/config.hcl", "run"]

# libp2p
EXPOSE 8000
# webapi
EXPOSE 8080
