//  Copyright (C) 2021-2023 Chronicle Labs, Inc.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Affero General Public License as
//  published by the Free Software Foundation, either version 3 of the
//  License, or (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Affero General Public License for more details.
//
//  You should have received a copy of the GNU Affero General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"io"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
)

var modelList = `
BTC/USD
ETH/BTC
ETH/USD
GNO/USD
IBTA/USD
LINK/USD
MATIC/USD
MKR/ETH
MKR/USD
RETH/ETH
RETH/USD
SDAI/DAI
STETH/ETH
USDC/USD
USDT/USD
WSTETH/ETH
WSTETH/USD
YFI/USD
`[1:]

func TestNewModelsCmd_List(t *testing.T) {
	stdout := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	os.Args = []string{"gofer", "-c", "../../config.hcl", "models"}
	main()

	os.Stdout = stdout

	_ = w.Close()
	out, _ := io.ReadAll(r)

	assert.Equal(t, modelList, string(out))
}

func TestNewModelsCmd(t *testing.T) {
	stdout := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	os.Args = []string{"gofer", "-c", "../../config.hcl", "models", "-o", "trace", "--no-color"}
	main()

	os.Stdout = stdout

	_ = w.Close()
	out, _ := io.ReadAll(r)

	assert.Equal(t, completeDataModels, string(out))
}

var completeDataModels = `
Model for BTC/USD:
───reference()
   └──median(min_values:3)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
Model for ETH/BTC:
───reference()
   └──median(min_values:3)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/BTC)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/BTC)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/BTC)
      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/BTC)
Model for ETH/USD:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      └──indirect()
         ├──alias(alias:ETH/USDC)
         │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
         └──reference()
            └──median(min_values:2)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
               └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for GNO/USD:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──alias(alias:ETH/GNO)
      │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:WETH/GNO)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      ├──indirect()
      │  ├──alias(alias:GNO/ETH)
      │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:GNO/WETH)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:GNO/BTC)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      └──indirect()
         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:GNO/USDT)
         └──reference()
            └──median(min_values:3)
               ├──indirect()
               │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
               │  └──reference()
               │     └──median(min_values:3)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
               │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
               ├──alias(alias:USDT/USD)
               │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
               └──indirect()
                  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
                  └──reference()
                     └──median(min_values:3)
                        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
                        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
                        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
                        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
Model for IBTA/USD:
───reference()
   └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:ishares, query:IBTA/USD)
Model for LINK/USD:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:LINK/BTC)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:LINK/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:LINK/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:LINK/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:LINK/USD)
      └──indirect()
         ├──alias(alias:LINK/ETH)
         │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:LINK/WETH)
         └──reference()
            └──median(min_values:3)
               ├──indirect()
               │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
               │  └──reference()
               │     └──median(min_values:3)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
               │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
               └──indirect()
                  ├──alias(alias:ETH/USDC)
                  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
                  └──reference()
                     └──median(min_values:2)
                        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
                        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for MATIC/USD:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:MATIC/USDT)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──alias(alias:USDT/USD)
      │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
      │        └──indirect()
      │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
      │           └──reference()
      │              └──median(min_values:3)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:MATIC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:MATIC/USD)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:huobi, query:MATIC/USDT)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──alias(alias:USDT/USD)
      │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
      │        └──indirect()
      │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
      │           └──reference()
      │              └──median(min_values:3)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:MATIC/USD)
Model for MKR/ETH:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:MKR/BTC)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/BTC)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/BTC)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/BTC)
      │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/BTC)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:MKR/USD)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:MKR/USD)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:MKR/USD)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      └──indirect()
         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:MKR/USD)
         └──reference()
            └──median(min_values:3)
               ├──indirect()
               │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
               │  └──reference()
               │     └──median(min_values:3)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
               │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
               └──indirect()
                  ├──alias(alias:ETH/USDC)
                  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
                  └──reference()
                     └──median(min_values:2)
                        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
                        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for MKR/USD:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:MKR/BTC)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:MKR/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:MKR/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:MKR/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:MKR/USD)
      ├──indirect()
      │  ├──alias(alias:MKR/ETH)
      │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:MKR/WETH)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      └──indirect()
         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:MKR/USDC)
         └──reference()
            └──median(min_values:2)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
               └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for RETH/ETH:
───reference()
   └──median(min_values:3)
      ├──alias(alias:RETH/ETH)
      │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:RETH/WETH)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:RETH/WSTETH)
      │  └──reference()
      │     └──indirect()
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
      │        └──reference()
      │           └──median(min_values:2)
      │              ├──alias(alias:STETH/ETH)
      │              │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
      │              └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:rocketpool, query:RETH/ETH)
Model for RETH/USD:
───reference()
   └──indirect()
      ├──reference()
      │  └──median(min_values:3)
      │     ├──alias(alias:RETH/ETH)
      │     │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:RETH/WETH)
      │     ├──indirect()
      │     │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:RETH/WSTETH)
      │     │  └──reference()
      │     │     └──indirect()
      │     │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
      │     │        └──reference()
      │     │           └──median(min_values:2)
      │     │              ├──alias(alias:STETH/ETH)
      │     │              │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
      │     │              └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
      │     └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:rocketpool, query:RETH/ETH)
      └──reference()
         └──median(min_values:3)
            ├──indirect()
            │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
            │  └──reference()
            │     └──median(min_values:3)
            │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
            │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
            │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
            │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
            └──indirect()
               ├──alias(alias:ETH/USDC)
               │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
               └──reference()
                  └──median(min_values:2)
                     ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
                     └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for SDAI/DAI:
───reference()
   └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:sdai, query:SDAI/DAI)
Model for STETH/ETH:
───reference()
   └──median(min_values:2)
      ├──alias(alias:STETH/ETH)
      │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
Model for USDC/USD:
───reference()
   └──median(min_values:2)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for USDT/USD:
───reference()
   └──median(min_values:3)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      ├──alias(alias:USDT/USD)
      │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
      └──indirect()
         ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
         └──reference()
            └──median(min_values:3)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
               └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
Model for WSTETH/ETH:
───reference()
   └──indirect()
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
      └──reference()
         └──median(min_values:2)
            ├──alias(alias:STETH/ETH)
            │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
            └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
Model for WSTETH/USD:
───reference()
   └──indirect()
      ├──reference()
      │  └──indirect()
      │     ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:wsteth, query:WSTETH/STETH)
      │     └──reference()
      │        └──median(min_values:2)
      │           ├──alias(alias:STETH/ETH)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:STETH/WETH)
      │           └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:curve, query:STETH/ETH)
      └──reference()
         └──median(min_values:3)
            ├──indirect()
            │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
            │  └──reference()
            │     └──median(min_values:3)
            │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
            │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
            │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
            │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
            ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
            └──indirect()
               ├──alias(alias:ETH/USDC)
               │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
               └──reference()
                  └──median(min_values:2)
                     ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
                     └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
Model for YFI/USD:
───reference()
   └──median(min_values:2)
      ├──indirect()
      │  ├──alias(alias:ETH/YFI)
      │  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:balancerV2, query:WETH/YFI)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
      │        └──indirect()
      │           ├──alias(alias:ETH/USDC)
      │           │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
      │           └──reference()
      │              └──median(min_values:2)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:YFI/USDT)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──alias(alias:USDT/USD)
      │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
      │        └──indirect()
      │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
      │           └──reference()
      │              └──median(min_values:3)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:YFI/USD)
      ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:YFI/USD)
      ├──indirect()
      │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:YFI/USDT)
      │  └──reference()
      │     └──median(min_values:3)
      │        ├──indirect()
      │        │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:BTC/USDT)
      │        │  └──reference()
      │        │     └──median(min_values:3)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │        │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │        │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      │        ├──alias(alias:USDT/USD)
      │        │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitfinex, query:UST/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:USDT/USD)
      │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDT/USD)
      │        └──indirect()
      │           ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:okx, query:BTC/USDT)
      │           └──reference()
      │              └──median(min_values:3)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
      │                 ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
      │                 └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
      └──indirect()
         ├──alias(alias:YFI/ETH)
         │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:sushiswap, query:YFI/WETH)
         └──reference()
            └──median(min_values:3)
               ├──indirect()
               │  ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:binance, query:ETH/BTC)
               │  └──reference()
               │     └──median(min_values:3)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:BTC/USD)
               │        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:BTC/USD)
               │        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:BTC/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:bitstamp, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:coinbase, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:ETH/USD)
               ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:ETH/USD)
               └──indirect()
                  ├──alias(alias:ETH/USDC)
                  │  └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:uniswapV3, query:WETH/USDC)
                  └──reference()
                     └──median(min_values:2)
                        ├──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:gemini, query:USDC/USD)
                        └──origin(expiry_threshold:5m0s, freshness_threshold:1m0s, origin:kraken, query:USDC/USD)

`[1:]
